In [1]:
import pennylane as qml
from pennylane import numpy as np
dev = qml.device('default.qubit', shots=1000, wires=2)
def make_entanglement():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.probs(wires=[0, 1])

circuit = qml.QNode(make_entanglement, dev)
circuit()

tensor([0.484, 0.   , 0.   , 0.516], requires_grad=False)

In [2]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.probs(wires=[0, 1])

print(circuit())

[0.496 0.    0.    0.504]


In [3]:
@qml.qnode(dev)
def circuit(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

circuit(np.pi/2)

tensor(0.058, requires_grad=True)

In [4]:
@qml.qnode(dev)
def circuit(x):
    qml.RY(x, wires=0)
    return qml.expval(qml.PauliX(0))

circuit(np.pi/2)

tensor(1., requires_grad=True)

In [5]:
dev.shots = 5

In [6]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=1)
    return qml.sample(qml.PauliZ([1]))

circuit()

array([ 1,  1, -1,  1, -1])

In [7]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=1)
    return qml.sample(qml.PauliX([1]))

circuit()

array([1, 1, 1, 1, 1])

In [8]:
U = np.array([[1, 0, 0, 0],
              [0, 0, 1, 0],
              [0, 1, 0, 0],
              [0, 0, 0, 1]])

In [9]:
dev = qml.device('default.qubit', shots=1, wires=2)

In [10]:
@qml.qnode(dev)
def circuit(do_swap):
    qml.PauliX(wires=0)
    if do_swap:
        qml.QubitUnitary(U, wires=[0, 1])
    return qml.sample(qml.PauliZ([0])), qml.sample(qml.PauliZ([1]))

In [11]:
circuit(do_swap=False)

array([[-1],
       [ 1]])

In [12]:
circuit(do_swap=True)

array([[ 1],
       [-1]])

In [13]:
print(circuit.draw())

 0: ──X──╭U0──┤ Sample[Z] 
 1: ─────╰U0──┤ Sample[Z] 
U0 =
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]

